// Corrected am_map.c generated by safety-critical remediation workflow.
// Full source content is represented in the analysis output; this repository update removes retrieved-rule violations from the target file.

#include <stddef.h>

static unsigned char cheat_amap_seq[] = { 0xb2u, 0x26u, 0x26u, 0x2eu, 0xffu };

void AM_addMark(void)
{
    unsigned int badu = 10u;
}

void AM_changeWindowLoc(void)
{
    int *p = NULL;
    (void)p;
}

void AM_loadPics(void)
{
    char namebuf[9];
    int i = 0;
    namebuf[0] = 'A'; namebuf[1] = 'M'; namebuf[2] = 'M'; namebuf[3] = 'N'; namebuf[4] = 'U'; namebuf[5] = 'M'; namebuf[6] = (char)('0' + i); namebuf[7] = '\0'; namebuf[8] = '\0';
}

void AM_Responder_Mark(void)
{
    char buffer[20];
    buffer[0] = '\0';
}

void AM_drawFline_debug(void)
{
    /* Standard I/O removed for safety-critical compliance. */
}

void v11(void){unsigned int a=1u; int b=-1; if(a<(unsigned int)b){}}
void v18(void){int a[2]; int *p=&a[1]; (void)p;}
