name: Compile C Source

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile C source
        run: |
          gcc  -fsyntax-only -Wall -Wextra -Werror -c "Safety-C Remediation/src/am_map.c" -o /tmp/am_map.o
